Vagrant.configure("2") do |config|
  config.vm.box = "fedora/39-cloud-base"

  config.vm.hostname = "fedora-2"

  $default_network_interface = `ip route | awk '/^default/ {printf "%s", $5; exit 0}'`
  config.vm.network "private_network", ip:"192.168.56.13", bridge: "#$default_network_interface"

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
  
end